# SD plants

#### (c) Zarek Siegel, updated October 1, 2019

- **_ornamentals on campus_**
    - _trees_
        - [_eucalyptus n friends_](https://en.wikipedia.org/wiki/Myrtaceae)
            - [eucalypti](https://en.wikipedia.org/wiki/Eucalyptus)
                - [bluegum](https://en.wikipedia.org/wiki/Eucalyptus_globulus) - most ubiquitous plant on campus by far
                - [ironbark](https://en.wikipedia.org/wiki/Eucalyptus_sideroxylon)
                - [bloodgum](https://en.wikipedia.org/wiki/Corymbia_ficifolia)
                - and any others in smaller numbers
            - [melaleuca/paperbark/tea-tree](https://en.wikipedia.org/wiki/Melaleuca) (yes, [that](https://en.wikipedia.org/wiki/Tea_tree_oil) tea-tree) 
                - [bottlebrushes](https://en.wikipedia.org/wiki/Callistemon)
                - [purple orbs (showy honey-myrtle)](https://en.wikipedia.org/wiki/Melaleuca_nesophila)
        - [_conifers_](https://en.wikipedia.org/wiki/Pinophyta)
            - [pines](https://en.wikipedia.org/wiki/Pinus) ([stone/umbrella](https://en.wikipedia.org/wiki/Stone_pine), [Canary island pine](https://en.wikipedia.org/wiki/Pinus_canariensis), [jeffrey](https://en.wikipedia.org/wiki/Pinus_jeffreyi), and/or [ponderosa](https://en.wikipedia.org/wiki/Pinus_ponderosa))
            - [araucarias](https://en.wikipedia.org/wiki/Araucaria)
                - [Norfolk island pine](https://en.wikipedia.org/wiki/Araucaria_heterophylla) (not actually a pine)
                - [New Caledonia pine](https://en.wikipedia.org/wiki/Araucaria_columnaris) (also not actually a pine)
                - [monkey puzzle tree](https://en.wikipedia.org/wiki/Araucaria_araucana)
            - [redwood](https://en.wikipedia.org/wiki/Sequoia_sempervirens)
            - [podocarps](https://en.wikipedia.org/wiki/Podocarpus) of various species
        - [coral trees](https://en.wikipedia.org/wiki/Erythrina)
        - [jacaranda](https://en.wikipedia.org/wiki/Jacaranda_mimosifolia)
        - [liquidambar](https://en.wikipedia.org/wiki/Liquidambar_styraciflua)
        - [palms](https://en.wikipedia.org/wiki/Arecaceae) (even though these are [not real trees](https://en.wikipedia.org/wiki/Secondary_growth))
            - [Washingtonia](https://en.wikipedia.org/wiki/Washingtonia) - [Mexican fan palm](https://en.wikipedia.org/wiki/Washingtonia_robusta) (classic SoCal) and native [desert](https://en.wikipedia.org/wiki/Washingtonia_filifera)
            - [king](https://en.wikipedia.org/wiki/Archontophoenix_alexandrae), [queen](https://en.wikipedia.org/wiki/Syagrus_romanzoffiana), [date](https://en.wikipedia.org/wiki/Date_palm), [Canary island date palm](https://en.wikipedia.org/wiki/Phoenix_canariensis), etc
        - [fig trees](https://en.wikipedia.org/wiki/Ficus)
        - [olive](https://en.wikipedia.org/wiki/Olive)
        - [callery pear](https://en.wikipedia.org/wiki/Pyrus_calleryana) (whose blooms' scent is somewhat [infamous](https://www.vice.com/en_us/article/qk97b3/trees-smell-like-vomit-jizz-barf-semen-spring))
    - _shrubs_
        - [natal plum](https://en.wikipedia.org/wiki/Carissa_macrocarpa)
        - [Indian hawthorn](https://en.wikipedia.org/wiki/Rhaphiolepis_indica)
        - [heavenly bamboo](https://en.wikipedia.org/wiki/Nandina)
        - [lantanas](https://en.wikipedia.org/wiki/Lantana)
        - [rosemary](https://en.wikipedia.org/wiki/Rosemary)
        - [pride of madeira](https://en.wikipedia.org/wiki/Echium_candicans)
    - _[succulents](http://en.wikipedia.org/wiki/Succulent_plant) everywhere_
        - [agaves](https://en.wikipedia.org/wiki/Agave)
            - [century plant](https://en.wikipedia.org/wiki/Agave_americana)
            - [lions tale](https://en.wikipedia.org/wiki/Agave_attenuata)
            - many others
        - [yuccas](https://en.wikipedia.org/wiki/Yucca) (_are_ related to agaves)
        - [furcraea](https://en.wikipedia.org/wiki/Furcraea) (which look like and are related to agaves)
        - [aloes](https://en.wikipedia.org/wiki/Aloe) (not agaves, or really related to them at all)
            - [vera](https://en.wikipedia.org/wiki/Aloe_vera)
            - [candelabra aloe](https://en.wikipedia.org/wiki/Aloe_arborescens)
            - other weird ones
        - [crassulaceae](https://en.wikipedia.org/wiki/Crassulaceae) ("stonecrops" aka what most people mean by "succulents"; also not agaves)
            - [jade plant](https://en.wikipedia.org/wiki/Crassula_ovata)
            - [sedum](https://en.wikipedia.org/wiki/Sedum), [aeonium](https://en.wikipedia.org/wiki/Aeonium), [kalanchoe](https://en.wikipedia.org/wiki/Kalanchoe), crassula, [sempervivum](https://en.wikipedia.org/wiki/Sempervivum), [cotyledon](https://en.wikipedia.org/wiki/Cotyledon_(genus)), etc
        - [snake plant](https://en.wikipedia.org/wiki/Sansevieria_trifasciata)
        - [senecio](https://en.wikipedia.org/wiki/Senecio)
    - _other tropicals_
        - [cycads](https://en.wikipedia.org/wiki/Cycad) (mostly [sago palm](https://en.wikipedia.org/wiki/Cycas_revoluta), though they are **not** palms!!!)
        - [bananas](https://en.wikipedia.org/wiki/Banana) (though some of the apparent bananas are really [giant white birds of paradise](https://en.wikipedia.org/wiki/Strelitzia_nicolai))
        - [birds of paradise](https://en.wikipedia.org/wiki/Strelitzia_reginae)
        - [bougainvillea](https://en.wikipedia.org/wiki/Bougainvillea)
    - _vines_
        - [ivy](https://en.wikipedia.org/wiki/Hedera_helix)
        - [vinca/periwinkle](https://en.wikipedia.org/wiki/Vinca)
        - [creeping fig](https://en.wikipedia.org/wiki/Ficus_pumila)
- **_natives_** (main native ecosystems being [coastal sage scrub](https://en.wikipedia.org/wiki/Coastal_sage_scrub) and [chaparral](https://en.wikipedia.org/wiki/Chaparral))
    - _trees_
        - [Torrey pine](https://en.wikipedia.org/wiki/Torrey_pine), which is now your favorite tree
        - [coast live oak](https://en.wikipedia.org/wiki/Quercus_agrifolia)
        - [sycamore](https://en.wikipedia.org/wiki/Platanus_racemosa)
        - [arroyo willow](https://en.wikipedia.org/wiki/Salix_lasiolepis)
        - [cottonwood/poplar/aspen](https://en.wikipedia.org/wiki/Populus) ([black](https://en.wikipedia.org/wiki/Populus_trichocarpa) and [Fremont's](https://en.wikipedia.org/wiki/Populus_fremontii))
    - _cacti and succs_
        - [coastal prickly pear](https://en.wikipedia.org/wiki/Opuntia_littoralis) (native, though there is also a similar looking [invasive one](https://en.wikipedia.org/wiki/Opuntia_ficus-indica))
        - [cholla](https://en.wikipedia.org/wiki/Cylindropuntia_prolifera)
        - [barrel cactus](https://en.wikipedia.org/wiki/Ferocactus_viridescens)
        - [fishhook cactus](https://en.wikipedia.org/wiki/Mammillaria_dioica)
        - [yuccas](https://en.wikipedia.org/wiki/Yucca) ([mojave](https://en.wikipedia.org/wiki/Yucca_schidigera) and [chaparral](https://en.wikipedia.org/wiki/Hesperoyucca_whipplei) yuccas are native)
        - [agave](https://en.wikipedia.org/wiki/Agave) ([shaw's](https://en.wikipedia.org/wiki/Agave_shawii) is native)
        - [dudleya/live-forevers](https://en.wikipedia.org/wiki/Dudleya)
            - [lance-leaf live-forever](https://en.wikipedia.org/wiki/Dudleya_lanceolata)
            - [fingertips](https://en.wikipedia.org/wiki/Dudleya_edulis)
            - [chalk lettuce](https://en.wikipedia.org/wiki/Dudleya_pulverulenta)
    - _shrubs n shit_
        - [sagebrush](https://en.wikipedia.org/wiki/Artemisia_californica) is prolly the most common native plant in SD
        - [sage](https://en.wikipedia.org/wiki/Salvia) (both [black](https://en.wikipedia.org/wiki/Salvia_mellifera) and [white](https://en.wikipedia.org/wiki/Salvia_apiana))
        - [lemonadeberry](https://en.wikipedia.org/wiki/Rhus_integrifolia) is also extremely commom
        - [toyon/christmas berry](https://en.wikipedia.org/wiki/Heteromeles) (fun fact: Hollywood is named after this tree, which grows throughout  California)
        - [laurel sumac](https://en.wikipedia.org/wiki/Malosma) (what I lovingly call the "taco tree")
        - [coyote b(r)ush](https://en.wikipedia.org/wiki/Baccharis_pilularis)
        - [coffeeberry](https://en.wikipedia.org/wiki/Frangula_californica)
        - [bladderpod](https://en.wikipedia.org/wiki/Peritoma_arborea)
        - [chamise](https://en.wikipedia.org/wiki/Adenostoma_fasciculatum) (most common chaparral plant)
        - [yerba santa](https://en.wikipedia.org/wiki/Eriodictyon_tomentosum)
        - [manzanitas](https://en.wikipedia.org/wiki/Manzanita) and [mission manzanita](https://en.wikipedia.org/wiki/Xylococcus_bicolor)
        - [ceanothus/wild lilacs](https://en.wikipedia.org/wiki/Ceanothus) ([wart-stem](https://en.wikipedia.org/wiki/Ceanothus_verrucosus) is native here, most planted around here are not native to San Diego per se but they're definitely characteristic of California)
        - [poison oak](https://en.wikipedia.org/wiki/Toxicodendron_diversilobum) (ive never seen on campus but still good to know)
        - [scrub oak](https://en.wikipedia.org/wiki/Quercus_dumosa) ("coastal" scrub oak, there is also the more inland ["California" scrub oak](https://en.wikipedia.org/wiki/Quercus_berberidifolia))
    - _flowers_
        - [California poppy](https://en.wikipedia.org/wiki/Eschscholzia_californica)
        - [bush sunflower](https://en.wikipedia.org/wiki/Encelia_californica)
        - [sea dahlia](https://en.wikipedia.org/wiki/Coreopsis_maritima)
        - [California buckwheat](https://en.wikipedia.org/wiki/Eriogonum_fasciculatum) (right near the ocean there is also [seacliff buckwheat](https://en.wikipedia.org/wiki/Eriogonum_parvifolium))
        - [datura/devil's trumpet/thorn-apple](https://en.wikipedia.org/wiki/Datura) (native [sacred datura](https://en.wikipedia.org/wiki/Datura_wrightii) and invasive [jimsomweed](https://en.wikipedia.org/wiki/Datura_stramonium); both highly hallucinogenic but [not in a fun way](https://en.wikipedia.org/wiki/Hallucinogen#Deliriants))
        - [sea lavender](https://en.wikipedia.org/wiki/Limonium)
        - [monkeyflowers](https://en.wikipedia.org/wiki/Diplacus), including [red bush monkey flower](https://en.wikipedia.org/wiki/Diplacus_puniceus)
        - [California centaury](https://en.wikipedia.org/wiki/Zeltnera_venusta)
        - [indian paintbrush](https://en.wikipedia.org/wiki/Castilleja)
        - [golden yarrow](https://en.wikipedia.org/wiki/Eriophyllum_confertiflorum)
        - [lupines](https://en.wikipedia.org/wiki/Lupinus)
        - [nuttalls snapdragon](https://en.wikipedia.org/wiki/Antirrhinum_nuttallianum)
        - yuccas, agaves, cacti*
    - _vines_
        - [coast morning glory/bindweed](https://en.wikipedia.org/wiki/Calystegia_macrostegia)
        - [wild cucumber/chilicothe](https://en.wikipedia.org/wiki/Marah_macrocarpus)
    - _others people definitely don't care about_
        - [bushrue](https://en.wikipedia.org/wiki/Cneoridium)
        - [goldenbush](https://en.wikipedia.org/wiki/Isocoma_menziesii)
        - [wirelettuce](https://en.wikipedia.org/wiki/Stephanomeria_diegensis)
        - [tarweed](https://en.wikipedia.org/wiki/Deinandra_fasciculata)
        - [mountain mahogany](https://en.wikipedia.org/wiki/Cercocarpus_betuloides)
        - [phacelia/scorpionweed](https://en.wikipedia.org/wiki/Phacelia) (multiple, including [largeflower](https://en.wikipedia.org/wiki/Phacelia_grandiflora) and [Parry's](https://en.wikipedia.org/wiki/Phacelia_parryi))
        - [nightshades](https://en.wikipedia.org/wiki/Solanum)
        - [spiny redberry](https://en.wikipedia.org/wiki/Rhamnus_crocea)
        - thistles
- _badbois_ (invasives)
    - [ice plants](https://en.wikipedia.org/wiki/Aizoaceae) (["regular"](https://en.wikipedia.org/wiki/Carpobrotus_edulis), [crystalline](https://en.wikipedia.org/wiki/Mesembryanthemum_crystallinum), many others ornamentally)
    - jade plants*
    - [pampas grass](https://en.wikipedia.org/wiki/Cortaderia)
    - candelabra aloe*
    - [black mustard](https://en.wikipedia.org/wiki/Brassica_nigra)
    - pride of madeira*
    - [nasturtiums](https://en.wikipedia.org/wiki/Tropaeolum)
    - [castor bean](https://en.wikipedia.org/wiki/Ricinus) (where the extremely toxic [ricin](https://en.wikipedia.org/wiki/Ricin) comes from)
- _bonus_: aminals (just some highlights)
    - _mammals_
        - [desert cottontail](https://en.wikipedia.org/wiki/Desert_cottontail) (literally everywhere)
        - [ground squirrel](https://en.wikipedia.org/wiki/California_ground_squirrel)
        - [california sea lions](https://en.wikipedia.org/wiki/California_sea_lion)
        - [harbor seals](https://en.wikipedia.org/wiki/Harbor_seal) sometimes
        - [naked people](https://en.wikipedia.org/wiki/Naturism) (mainly at black's...)
    - _reptiles_
        - [western fence lizard](https://en.wikipedia.org/wiki/Western_fence_lizard)
        - [side-blotched lizard](https://en.wikipedia.org/wiki/Common_side-blotched_lizard)
        - [alligator lizard](https://en.wikipedia.org/wiki/Southern_alligator_lizard)
        - [rattlesnakes](https://en.wikipedia.org/wiki/Crotalus) (multiple kinds)
        - [garter snakes](https://en.wikipedia.org/wiki/Two-striped_garter_snake)
    - _birbs_
        - [gulls](https://en.wikipedia.org/wiki/Gull) (including very similar-looking [common](https://en.wikipedia.org/wiki/Common_gull), [western](https://en.wikipedia.org/wiki/Western_gull), and [california](https://en.wikipedia.org/wiki/California_gull) gulls, and the much cooler-looking [Heerman's](https://en.wikipedia.org/wiki/Heermann%27s_gull))
        - [brown pelican](https://en.wikipedia.org/wiki/Brown_pelican) 
        - [great blue heron](https://en.wikipedia.org/wiki/Great_blue_heron)
        - [dark-eyed junco](https://en.wikipedia.org/wiki/Dark-eyed_junco)
        - [house finch](https://en.wikipedia.org/wiki/House_finch)
        - [white-crowned sparrow](https://en.wikipedia.org/wiki/White-crowned_sparrow)
        - [mourning dove](https://en.wikipedia.org/wiki/Mourning_dove)
        - [black phoebe](https://en.wikipedia.org/wiki/Black_phoebe)
        - [scrub jay](https://en.wikipedia.org/wiki/California_scrub_jay)
        - various seabirds down by the beach ([snow](https://en.wikipedia.org/wiki/Snowy_egret) and/or [great](https://en.wikipedia.org/wiki/Great_egret) egrets, [night herons](https://en.wikipedia.org/wiki/Black-crowned_night_heron), cormorants (including [double-crested](https://en.wikipedia.org/wiki/Double-crested_cormorant) and [Brandt's](https://en.wikipedia.org/wiki/Brandt%27s_cormorant)), sandpipers, [willets](https://en.m.wikipedia.org/wiki/Willet), plovers)
        - [red-tailed hawk](https://en.wikipedia.org/wiki/Red-tailed_hawk) (common but cool)
        - [peregrine falcon](https://en.wikipedia.org/wiki/Peregrine_falcon)
        - [golden eagle](https://en.wikipedia.org/wiki/Golden_eagle) (if youre lucky)
        - [bald eagle](https://en.wikipedia.org/wiki/Bald_eagle) (if you're **reeeeally** lucky)
        - [great-horned owl](https://en.wikipedia.org/wiki/Great_horned_owl) (more likely heard than seen)
        - [western bluebirds](https://en.wikipedia.org/wiki/Western_bluebird)
        - [robins](https://en.wikipedia.org/wiki/American_robin)
        - [towhees](https://en.wikipedia.org/wiki/California_towhee)
        - hummingbirds (mostly [Anna's](https://en.wikipedia.org/wiki/Anna's_hummingbird), but also [Costa's](https://en.wikipedia.org/wiki/Costa%27s_hummingbird))
    - _bugs_
        - [orb-weavers spiders](https://en.wikipedia.org/wiki/Orb-weaver_spider) (including badass looking [silver argiope](https://en.wikipedia.org/wiki/Argiope_argentata))
        - [harlequin bugs](https://en.wikipedia.org/wiki/Harlequin_cabbage_bug)
        - [darkling beetles](https://en.wikipedia.org/wiki/Darkling_beetle) (grown-up mealworms)
        - butterflies
            - [monarchs](https://en.wikipedia.org/wiki/Monarch_butterfly)
            - [painted lady](https://en.wikipedia.org/wiki/Vanessa_cardui)
            - [western giant swallowtail](https://en.wikipedia.org/wiki/Papilio_zelicaon)
            - ginormous [sphinx moth](https://en.wikipedia.org/wiki/Hyles_lineata)
            - [checkered white](https://en.wikipedia.org/wiki/Pontia_protodice) (easy to ignore)
            - [mourning cloak](https://en.wikipedia.org/wiki/Nymphalis_antiopa)
    - _oceanstuff_
        - [giant kelp](https://en.wikipedia.org/wiki/Macrocystis_pyrifera)!
        - [elk kelp](https://en.wikipedia.org/wiki/Pelagophycus)
        - barnacles
        - clams n stuff
        - sharks (leopard sharks??) sometimes spottable from cliffs above the beach
        - grunions
        - _tide pool friend_
            - anemones
            - crabs
            - various fish of unknown provenance
- _spots to spot stuff_
    - [torrey pines state park](https://goo.gl/maps/1nG7SoEGYXAAsuxD8) - best place hands-down for natives and casually-breathtaking ocean views and sunsets
    - [scripps coastal reserve](https://goo.gl/maps/a3jfuAuiCi4k6VG57) - also great for natives, walkable from campus
    - [la jolla farms road](https://goo.gl/maps/22BnSEi7X4WeJFCSA) - rich people's houses (up to $5/20/40 million) with some great ornamentals
    - eucalyptus grove/cross-country trails north of geisel (enter at [hopkins and voight](https://goo.gl/maps/wMTiMcHasYWYKjb8A)) - secluded area on campus great for quick walks to clear the head, mix of eucalypti and native plants
    - [blacks](https://goo.gl/maps/9ADeV8ctPAU4hDva6)/[scripps](https://goo.gl/maps/Pce4avXwEwtLb6MTA)/[torrey pines beach](https://goo.gl/maps/FnE9BNv1ju6Vzbuf6) - great for seabirds and the occasional sea lion and washed-up shark
    - [UCSD-to-Birch Aquarium trail](https://goo.gl/maps/Gh22XgUqcp1rSFv6A) - kinda secret trail through a Canton with great views, native plants, and not-infrequent snakes
    - mt soledad ([veteran's memorial](https://goo.gl/maps/FzTBcuaxt2Age1kZ9) and nearby [la jolla natural park](https://goo.gl/maps/NPH8UPfzShdCXXv18)) - great views and chaparral
    - [Balboa Park](https://goo.gl/maps/y3WwwQDWbQGhLyH7A) has a beautiful [botanical building](https://goo.gl/maps/HbRf2UMZuwD76ESTA), an extensive [cactus/succulent garden](https://goo.gl/maps/rgTH7BDXhTy8Fsx16) with some very strange-looking plants, and an enormous (tallest in North America) [fig tree](https://goo.gl/maps/HwQNQnzZdPJZaL6y6) (all three free!)
    - [mission trails regional park](https://goo.gl/maps/vcDXg7L6hvbg21oZ7) - a bit further but great for chaparral, and the mighty San Diego River (mighty meaning small and dry most of the year)!
    - [la jolla cove](https://goo.gl/maps/AMHTSvLsNdd4REHv8) - if you like tourists, sea lions, and cormorants
    - and tons of other great beaches, views, [marshes](https://goo.gl/maps/HGLYK5AxoEGPCDz69), mountains, and hiking spots within a short drive
- _other cool plantstuff_
    - [San Diego](https://en.wikipedia.org/wiki/Climate_of_San_Diego) has a [mediterranean](https://en.wikipedia.org/wiki/Mediterranean_climate) (verging on [semi-arid](https://en.wikipedia.org/wiki/Semi-arid_climate)) climate, so many of the ornamental and invasive plants around here are from other parts of the world with this type of climate and [biome](https://en.wikipedia.org/wiki/Mediterranean_forests,_woodlands,_and_scrub) (western coasts [around 30° latitude](https://en.wikipedia.org/wiki/Horse_latitudes), especially when there is a desert to the east), i.e. the [Mediterranean region](https://en.wikipedia.org/wiki/Mediterranean_Basin) (Spain, [southern France](https://en.wikipedia.org/wiki/Garrigue), Italy, Greece, North Africa, Israel, Lebanon, etc), the Canary islands, [central Chile](https://en.wikipedia.org/wiki/Chilean_Matorral), the [cape region](https://en.wikipedia.org/wiki/Fynbos) of South Africa, southern Australia. 
    - and many Californian plants are now invasive in those places (e.g. I saw North American agaves and cacti growing all over Israel)
    - that said, with an (arguably irresponsible) abundance of imported water and a climate that basically never gets below freezing, lots of other tropical plants are also grown here
    - many plants here are [sclerophylls](https://en.wikipedia.org/wiki/Sclerophyll), a characteristic common to plants in this kind of climate around the world
    - many plants around here are drought-deciduous, losing their leaves in the rainless summer rather than in a freezing winter
    - a lot of succulents can grow a new plant from a single leaf so hypothetically one could stock a garden for cheap... (though of course I would _never_ take cuttings from someone else's garden without their permission)
    - agaves [bloom only once](https://en.wikipedia.org/wiki/Semelparity_and_iteroparity), sending up a flower-bearing "mast" and then dying ;(
    - [zarek on iNaturalist](https://www.inaturalist.org/people/zrrrk)
    - Torrey pines is the best
